#!/usr/bin/env sh

# uint utils_create (string <filepath>)
#
# Creates a file.
#
# R : 0 - success
#     1 - file already exists
#     2 - creation failed
#
function utils_create {
	[[ -f $1 ]] && return 1
	: > "$1" || return 2
	return 0
}
