#!/usr/bin/env sh
: ${DEBUG:=1}

_exit() { echo -e "Error: $*" ; echo "" ; exit 1
} ; [[ -z "$QPROJECT" ]] && _exit " This program component cannot be run. Import it from QPX Framework. "


include globals
include log
include null

#
# misc
#
# Miscellaneous functions.
#

# void mark (string <key>, [string <value>])
#
function mark {
	log_fcall "$@"

	if [[ -n $2 ]]; then
		echo "$2" > "$GLOBALS_LOGDIR/$1" 2>&"$NULL"
	elif [[ -n ${!1} ]]; then
		echo "${!1}" > "$GLOBALS_LOGDIR/$1" 2>&"$NULL"
	else
		: > "$GLOBALS_LOGDIR/$1"
	fi
}


# void unmark (string <key>)
#
function unmark {
	log_fcall "$@"
	rm -f "$GLOBALS_LOGDIR/$1"
}


# void dumpvariables (void)
#
# > string __ = file path
#
function dumpvariables {
	log_fcall "$@"
	__=$GLOBALS_VARDUMP
	set | grep '^[[:alpha:][:digit:]_]\+=' > "$__"
}


# void dumpfunctions (void)
#
# > string __ = file path
#
function dumpfunctions {
	log_fcall "$@"
	__=$GLOBALS_FUNCDUMP
	set | sed -n '/^[[:alpha:][:digit:]_]\+[[:blank:]]*()/,/^}/p' > "$__"
}
