#!/usr/bin/env sh

_exit() { echo -e "Error: $*" ; echo "" ; exit 1
} ; [[ -z "$QPROJECT" ]] && _exit " This program component cannot be run. Import it from QPX Framework. "


include fd

NULL=0

# void null_open (void)
#
function null_open {
	eval "exec $NULL<>/dev/null"
}


# void null_close (void)
#
function null_close {
	eval "exec $NULL<&-"$'\n'"exec $NULL>&-"
}


{
	fd_new
	NULL=$?
	null_open
}
