#!/usr/bin/env sh
: ${DEBUG:=1}

_exit() { echo -e "Error: $*" ; echo "" ; exit 1
} ; [[ -z "$QPROJECT" ]] && _exit " This program component cannot be run. Import it from QPX Framework. "


include useextglob

# Provides common patterns.
#
PATTERNS_ALPHA='+([[:alpha:]])'
PATTERNS_LOWER='+([[:lower:]])'
PATTERNS_UPPER='+([[:upper:]])'
PATTERNS_DIGIT='+([[:digit:]])'
PATTERNS_ALNUM='+([[:alnum:]])'
PATTERNS_BLANK='+([[:blank:]])'
PATTERNS_SPACE='+([[:space:]])'
PATTERNS_PUNCT='+([[:punct:]])'

PATTERNS_VARIABLENAME='[[:alpha:]_]*([[:alnum:]_])'
PATTERNS_ARRAYVARNAME='[[:alpha:]_]*([[:alnum:]_])'
PATTERNS_SUBARRAYNAME='[[:alpha:]_]*([[:alnum:]_])@(\[+([[:digit:]])\])'
PATTERNS_MIXEDVARNAME='[[:alpha:]_]*([[:alnum:]_])?(\[+([[:digit:]])\])'
PATTERNS_FUNCTIONNAME='[[:alpha:]-:_]*([[:alnum:]-:_])'	## ':' appears to be sensitive with its position

PATTERNS_NUMBER='+([[:digit:]])'
PATTERNS_INTEGER='?(-)+([[:digit:]])'
PATTERNS_SIGNEDINTEGER='?(-)+([[:digit:]])'
PATTERNS_UNSIGNEDINTEGER='+([[:digit:]])'
PATTERNS_DECIMAL='?([[:digit:]]).+([[:digit:]])'

PATTERNS_FILENAME='+([[:alnum:][:blank:][:punct:]])'	## we can't really tell
PATTERNS_FILEPATH=$PATTERNS_FILENAME'!(/)'
