#!/usr/bin/env sh
: ${DEBUG:=1}

_exit() { echo -e "Error: $*" ; echo "" ; exit 1
} ; [[ -z "$QPROJECT" ]] && _exit " This program component cannot be run. Import it from QPX Framework. "


include console
include null

#
# reset
#

# void reset (void)
#
function reset {
	local RESET=''

	[[ $(type -t reset) = file ]] && \
		RESET=$(command reset)
	[[ -z $RESET ]] && type -t tput >&"$NULL" && \
		RESET=$(exec tput reset)

	if [[ -n $RESET ]]; then
		eval "function reset { echo -en '$RESET'; }"
		echo -en "$RESET"
	fi
}
